services:
  app:
    build:
      context: .
      args:
        VITE_API_BASE_URL: http://localhost:8081/api/v1
    ports:
      - "8081:8081"
    container_name: vendasonline-app
    volumes:
      - ./logs:/app/logs
